name: Release

on:
  push:
    branches: 
    - main
    
jobs:
  machine-matrix:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        machine: [raspberrypi3-64, raspberrypi4-64, reterminal-64 ]
      
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clone required dependencies
        run: ./repo-mgr.sh init
      
      - name: Source build environment
        run:  source ./poky/oe-init-build-env build
      
      - name: Build Yocto images
        run:  |
          MACHINE=${{ matrix.machine }} bitbake bitbake dotnet-image-minimal --dry-run
          MACHINE=${{ matrix.machine }} bitbake bitbake dotnet-image-full --dry-run
            
      - name: Disk space report after build
        run: |
          echo "Memory and swap:"
          free
          echo
          swapon --show
          echo
          echo "Available storage:"
          df -h
          echo
          
