name: Release

on:
  push:
    branches: 
    - main
    
jobs:
  machine-matrix:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clone required dependencies
        run: ./repo-mgr.sh init
            
      - name: Build Yocto images
        run:  |
          source ./poky/oe-init-build-env build
          bitbake dotnet-image-minimal --dry-run
          
      - name: Create the package index
        run:  bitbake package-index
        
      - name: Disk space report after build
        run: |
          echo "Memory and swap:"
          free
          echo
          swapon --show
          echo
          echo "Available storage:"
          df -h
          echo
          
